"""empty message

Revision ID: 8127999aa1e8
Revises: 4cf28c76d4f9
Create Date: 2017-05-08 13:23:37.977579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8127999aa1e8'
down_revision = '4cf28c76d4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title')
    )
    op.add_column(u'task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    op.add_column(u'team', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column(u'team', 'project_id')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column(u'task', 'project_id')
    op.drop_table('project')
    # ### end Alembic commands ###
