"""empty message

Revision ID: ffeaddde796a
Revises: b1b559f3e1e0
Create Date: 2017-05-08 13:12:00.168443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffeaddde796a'
down_revision = 'b1b559f3e1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('secondary_email', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=True))
    op.drop_index('password', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('password', 'user', ['password'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'secondary_email')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
